<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>EkranZamani</RootNamespace>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EkranZamani.Tests" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.1" />
  </ItemGroup>

</Project>
